### ISSUE TITLE
Shell Upload Vulnerability in the Testing.php Script !

### ISSUE THREAD

**Issue by TheBlaCkCoDeR09** [MohamedAmine-C/File-Uploader#2]
You should Add more Lines to Create a Good Filter! I can use a Malicious PHP File alongside the JPG Extension as an Example and then i can Upload it and Trick the WebApp! And Done i got access to the Website and it's Hacked Now !

**Comment by MohamedAmine-C** [comment]
@TheBlaCkCoDeR09  

Hello i'm sorry i have never seen this issue till now,
i've checked and tried to upload a file with (.php) extension but an error is thrown so everything is working fine here.
Please confirme this issue with more info.

thank you.

**Comment by MohamedAmine-C** [comment]
after testing this reported bug, everything went all right so this issue will be closed
